[project]
name = "modin-vs-pandas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "modin[all]>=0.32.0",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
]
